/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ReviewRouteImport } from './routes/review'
import { Route as ResultsRouteImport } from './routes/results'
import { Route as ReportRouteImport } from './routes/report'
import { Route as ReliabilityRouteImport } from './routes/reliability'
import { Route as RecruiterRouteImport } from './routes/recruiter'
import { Route as MethodologyRouteImport } from './routes/methodology'
import { Route as ItemsRouteImport } from './routes/items'
import { Route as AssessmentRouteImport } from './routes/assessment'
import { Route as AssessRouteImport } from './routes/assess'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ATokenRouteImport } from './routes/a.$token'

const ReviewRoute = ReviewRouteImport.update({
  id: '/review',
  path: '/review',
  getParentRoute: () => rootRouteImport,
} as any)
const ResultsRoute = ResultsRouteImport.update({
  id: '/results',
  path: '/results',
  getParentRoute: () => rootRouteImport,
} as any)
const ReportRoute = ReportRouteImport.update({
  id: '/report',
  path: '/report',
  getParentRoute: () => rootRouteImport,
} as any)
const ReliabilityRoute = ReliabilityRouteImport.update({
  id: '/reliability',
  path: '/reliability',
  getParentRoute: () => rootRouteImport,
} as any)
const RecruiterRoute = RecruiterRouteImport.update({
  id: '/recruiter',
  path: '/recruiter',
  getParentRoute: () => rootRouteImport,
} as any)
const MethodologyRoute = MethodologyRouteImport.update({
  id: '/methodology',
  path: '/methodology',
  getParentRoute: () => rootRouteImport,
} as any)
const ItemsRoute = ItemsRouteImport.update({
  id: '/items',
  path: '/items',
  getParentRoute: () => rootRouteImport,
} as any)
const AssessmentRoute = AssessmentRouteImport.update({
  id: '/assessment',
  path: '/assessment',
  getParentRoute: () => rootRouteImport,
} as any)
const AssessRoute = AssessRouteImport.update({
  id: '/assess',
  path: '/assess',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ATokenRoute = ATokenRouteImport.update({
  id: '/a/$token',
  path: '/a/$token',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/assess': typeof AssessRoute
  '/assessment': typeof AssessmentRoute
  '/items': typeof ItemsRoute
  '/methodology': typeof MethodologyRoute
  '/recruiter': typeof RecruiterRoute
  '/reliability': typeof ReliabilityRoute
  '/report': typeof ReportRoute
  '/results': typeof ResultsRoute
  '/review': typeof ReviewRoute
  '/a/$token': typeof ATokenRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/assess': typeof AssessRoute
  '/assessment': typeof AssessmentRoute
  '/items': typeof ItemsRoute
  '/methodology': typeof MethodologyRoute
  '/recruiter': typeof RecruiterRoute
  '/reliability': typeof ReliabilityRoute
  '/report': typeof ReportRoute
  '/results': typeof ResultsRoute
  '/review': typeof ReviewRoute
  '/a/$token': typeof ATokenRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/assess': typeof AssessRoute
  '/assessment': typeof AssessmentRoute
  '/items': typeof ItemsRoute
  '/methodology': typeof MethodologyRoute
  '/recruiter': typeof RecruiterRoute
  '/reliability': typeof ReliabilityRoute
  '/report': typeof ReportRoute
  '/results': typeof ResultsRoute
  '/review': typeof ReviewRoute
  '/a/$token': typeof ATokenRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/assess'
    | '/assessment'
    | '/items'
    | '/methodology'
    | '/recruiter'
    | '/reliability'
    | '/report'
    | '/results'
    | '/review'
    | '/a/$token'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/assess'
    | '/assessment'
    | '/items'
    | '/methodology'
    | '/recruiter'
    | '/reliability'
    | '/report'
    | '/results'
    | '/review'
    | '/a/$token'
  id:
    | '__root__'
    | '/'
    | '/assess'
    | '/assessment'
    | '/items'
    | '/methodology'
    | '/recruiter'
    | '/reliability'
    | '/report'
    | '/results'
    | '/review'
    | '/a/$token'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AssessRoute: typeof AssessRoute
  AssessmentRoute: typeof AssessmentRoute
  ItemsRoute: typeof ItemsRoute
  MethodologyRoute: typeof MethodologyRoute
  RecruiterRoute: typeof RecruiterRoute
  ReliabilityRoute: typeof ReliabilityRoute
  ReportRoute: typeof ReportRoute
  ResultsRoute: typeof ResultsRoute
  ReviewRoute: typeof ReviewRoute
  ATokenRoute: typeof ATokenRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/review': {
      id: '/review'
      path: '/review'
      fullPath: '/review'
      preLoaderRoute: typeof ReviewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/results': {
      id: '/results'
      path: '/results'
      fullPath: '/results'
      preLoaderRoute: typeof ResultsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/report': {
      id: '/report'
      path: '/report'
      fullPath: '/report'
      preLoaderRoute: typeof ReportRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reliability': {
      id: '/reliability'
      path: '/reliability'
      fullPath: '/reliability'
      preLoaderRoute: typeof ReliabilityRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/recruiter': {
      id: '/recruiter'
      path: '/recruiter'
      fullPath: '/recruiter'
      preLoaderRoute: typeof RecruiterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/methodology': {
      id: '/methodology'
      path: '/methodology'
      fullPath: '/methodology'
      preLoaderRoute: typeof MethodologyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/items': {
      id: '/items'
      path: '/items'
      fullPath: '/items'
      preLoaderRoute: typeof ItemsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/assessment': {
      id: '/assessment'
      path: '/assessment'
      fullPath: '/assessment'
      preLoaderRoute: typeof AssessmentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/assess': {
      id: '/assess'
      path: '/assess'
      fullPath: '/assess'
      preLoaderRoute: typeof AssessRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/a/$token': {
      id: '/a/$token'
      path: '/a/$token'
      fullPath: '/a/$token'
      preLoaderRoute: typeof ATokenRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AssessRoute: AssessRoute,
  AssessmentRoute: AssessmentRoute,
  ItemsRoute: ItemsRoute,
  MethodologyRoute: MethodologyRoute,
  RecruiterRoute: RecruiterRoute,
  ReliabilityRoute: ReliabilityRoute,
  ReportRoute: ReportRoute,
  ResultsRoute: ResultsRoute,
  ReviewRoute: ReviewRoute,
  ATokenRoute: ATokenRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
